# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f9J9ixYJcPPT3qMpDAc9L5PK9795U7v

**FA23-BBD-160**

**M.Zakariya Adil**

**BBD-6B LAB FINAL DEEP LEARNING**
"""

!pip install -q streamlit pyngrok imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve
)

from imblearn.over_sampling import SMOTE

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import warnings
warnings.filterwarnings('ignore')

uploaded = files.upload()

df = pd.read_csv('creditcard.csv')

df.head()

print(df.shape)

print(df.columns)

df.info()

df.isnull().sum()

plt.figure(figsize=(6,4))

sns.countplot(x='Class', data=df)

plt.title('Fraud vs Non-Fraud Transactions')

plt.show()

print(df['Class'].value_counts())

scaler = StandardScaler()

df['Amount'] = scaler.fit_transform(df[['Amount']])

df['Time'] = scaler.fit_transform(df[['Time']])

X = df.drop('Class', axis=1)

y = df['Class']

smote = SMOTE(random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

print(y.value_counts())

print(y_resampled.value_counts())

X_train, X_test, y_train, y_test = train_test_split(
    X_resampled,
    y_resampled,
    test_size=0.2,
    random_state=42,
    stratify=y_resampled
)

model = Sequential()

model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))

model.add(Dropout(0.3))

model.add(Dense(32, activation='relu'))

model.add(Dropout(0.3))

model.add(Dense(16, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=256,
    callbacks=[early_stop],
    verbose=1
)

plt.figure(figsize=(12,5))

# Accuracy Graph
plt.subplot(1,2,1)

plt.plot(history.history['accuracy'])

plt.plot(history.history['val_accuracy'])

plt.title('Model Accuracy')

plt.xlabel('Epoch')

plt.ylabel('Accuracy')

plt.legend(['Train', 'Validation'])

# Loss Graph
plt.subplot(1,2,2)

plt.plot(history.history['loss'])

plt.plot(history.history['val_loss'])

plt.title('Model Loss')

plt.xlabel('Epoch')

plt.ylabel('Loss')

plt.legend(['Train', 'Validation'])

plt.show()

y_pred_prob = model.predict(X_test)

y_pred = (y_pred_prob > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Precision:", precision_score(y_test, y_pred))

print("Recall:", recall_score(y_test, y_pred))

print("F1 Score:", f1_score(y_test, y_pred))

print("ROC AUC Score:", roc_auc_score(y_test, y_pred_prob))

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.xlabel('Predicted')

plt.ylabel('Actual')

plt.title('Confusion Matrix')

plt.show()

fpr, tpr, thresholds = roc_curve(y_test, y_pred_prob)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr)

plt.plot([0,1], [0,1], '--')

plt.xlabel('False Positive Rate')

plt.ylabel('True Positive Rate')

plt.title('ROC Curve')

plt.show()

model.save('credit_card_fraud_model.h5')

files.download('credit_card_fraud_model.h5')

import streamlit as st
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import StandardScaler

# Load model
model = tf.keras.models.load_model('credit_card_fraud_model.h5')

st.title('Credit Card Fraud Detection App')

st.write('Upload a CSV file for fraud prediction')

uploaded_file = st.file_uploader('Upload CSV File', type=['csv'])

if uploaded_file is not None:

    df = pd.read_csv(uploaded_file)

    st.subheader('Uploaded Dataset')

    st.write(df.head())

    # Remove target column if exists
    if 'Class' in df.columns:
        df = df.drop('Class', axis=1)

    # Feature scaling
    scaler = StandardScaler()

    if 'Amount' in df.columns:
        df['Amount'] = scaler.fit_transform(df[['Amount']])

    if 'Time' in df.columns:
        df['Time'] = scaler.fit_transform(df[['Time']])

    # Predictions
    predictions = model.predict(df)

    predicted_classes = (predictions > 0.5).astype(int)

    df['Fraud_Prediction'] = predicted_classes

    st.subheader('Prediction Results')

    st.write(df)

    fraud_count = (df['Fraud_Prediction'] == 1).sum()

    non_fraud_count = (df['Fraud_Prediction'] == 0).sum()

    st.success(f'Fraud Transactions: {fraud_count}')

    st.success(f'Non Fraud Transactions: {non_fraud_count}')

    csv = df.to_csv(index=False).encode('utf-8')

    st.download_button(
        label='Download Results',
        data=csv,
        file_name='fraud_predictions.csv',
        mime='text/csv'
    )

